CREATE DATABASE IF NOT EXISTS cinema_system;

USE cinema_system;

CREATE USER IF NOT EXISTS 'Admin'@'localhost' IDENTIFIED BY 'AdminIsHere';
GRANT ALL PRIVILEGES ON cinema_system.* TO 'Admin'@'localhost';

CREATE USER IF NOT EXISTS 'User'@'localhost' IDENTIFIED BY 'UserIsHere';
GRANT SELECT ON cinema_system.* TO 'User'@'localhost';

CREATE TABLE IF NOT EXISTS roles(
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  role_name VARCHAR(10)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS users(
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  firstname VARCHAR(50) NOT NULL,
  lastname VARCHAR(50) NOT NULL,
  email VARCHAR(254) NOT NULL UNIQUE KEY,
  password VARCHAR(60) NOT NULL,
  date_of_birth DATE,
  id_role INT NOT NULL,
  FOREIGN KEY (id_role) REFERENCES roles(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS rate(
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  description VARCHAR(50) NOT NULL,
  price DECIMAL(4,2) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS cinema(
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(50) NOT NULL,
  address VARCHAR(50) NOT NULL UNIQUE KEY
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS movies(
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(50) NOT NULL,
  genre VARCHAR(30) NOT NULL,
  duration VARCHAR(4) NOT NULL,
  year_release VARCHAR(4) NOT NULL,
  director VARCHAR(60)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS hall(
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  room_name VARCHAR(4) NOT NULL UNIQUE KEY,
  seating_capacity INT NOT NULL,  
  id_cinema INT NOT NULL, 
  FOREIGN KEY (id_cinema) REFERENCES cinema(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS session(
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  date_session DATE NOT NULL,
  start_time TIME NOT NULL,
  end_time TIME NOT NULL,
  id_movie INT NOT NULL,
  id_hall INT NOT NULL,
  FOREIGN KEY (id_movie) REFERENCES movies(id),
  FOREIGN KEY (id_hall) REFERENCES hall(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS ticket(
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  seat_number INT NOT NULL UNIQUE KEY,
  id_user INT NOT NULL,
  id_rate INT NOT NULL,
  id_session INT NOT NULL,
  FOREIGN KEY (id_user) REFERENCES users(id),
  FOREIGN KEY (id_rate) REFERENCES rate(id),
  FOREIGN KEY (id_session) REFERENCES session(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;